name: Kompiluj i wdrażaj aplikację .NET w aplikacji kontenera egabinet-app
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: egabinet-app-container
  CONTAINER_APP_NAME: egabinet-app
  CONTAINER_APP_RESOURCE_GROUP_NAME: egabinet-app-ResourceGroup
  CONTAINER_REGISTRY_LOGIN_SERVER: egabinet20230218220414.azurecr.io
  DOCKER_FILE_PATH: Egabinet/Dockerfile
  PROJECT_NAME_FOR_DOCKER: egabinet
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test with the dotnet CLI
      run: dotnet test
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v3
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.Egabinet20230218220414_USERNAME_D3B1 }}
        password: ${{ secrets.Egabinet20230218220414_PASSWORD_D3B1 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.egabinet_app_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.Egabinet20230218220414_USERNAME_D3B1 }} --password ${{ secrets.Egabinet20230218220414_PASSWORD_D3B1 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
