name: Kompiluj i wdrażaj aplikację .NET w aplikacji kontenera egabinet-app
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: egabinet-app-container
  CONTAINER_APP_NAME: egabinet-app
  CONTAINER_APP_RESOURCE_GROUP_NAME: egabinet-app-ResourceGroup
  CONTAINER_REGISTRY_LOGIN_SERVER: egabinet20230218220414.azurecr.io
  DOCKER_FILE_PATH: Egabinet/Dockerfile
  PROJECT_NAME_FOR_DOCKER: egabinet
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.egabinet_app_SPN }}
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          agentIP=$(curl -s https://api.ipify.org/)

          az sql server firewall-rule create -g egabinet-app-ResourceGroup -s egabinetdbserver -n githubAction --end-ip-address $agentIP --end-ip-address $agentIP

          sleep 300

          dotnet tool install --global dotnet-ef

          dotnet tool restore

          dotnet ef database update -p Egabinet --connection ${{ secrets.DBCONNECTION }}

          az sql server firewall-rule delete -r egabinet-app-ResourceGroup -s egabinetdbserver -n githubAction 
    - name: logout
      run: >
        az logout



          